name: flutter_application_3
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  auto_size_text: ^3.0.0
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  cloud_firestore: ^5.6.1
  crypto: ^3.0.6
  cupertino_icons: ^1.0.8
  easy_localization: ^3.0.3
  firebase_auth: ^5.4.0
  firebase_core: ^3.10.0
  firebase_storage: ^12.4.2
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.6
  google_fonts: ^6.2.1
  html_unescape: ^2.0.0
  http: ^1.3.0
  image_picker: ^1.1.2
  marquee: ^2.3.0
  provider: ^6.1.2
  shared_preferences: ^2.5.2
  smooth_page_indicator: ^1.2.0+3
  url_launcher: ^6.3.1
  webview_flutter: ^4.10.0
  yahoo_finance_data_reader: ^1.0.11

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
